#define IDH_CopiaCopy 100
#define IDH_ComandiGEOsim 101
#define IDH_Inserimentoentit 102
#define IDH_Impostavalorididefaultattributi 103
#define IDH_Importaoggetti 104
#define IDH_Importazioneentitdafile 105
#define IDH_Importazioneentitdagrafica 106
#define IDH_NoteperladigitalizzazioneinAutoCADMap 107
#define IDH_MostraeNascondiattributi 108
#define IDH_AggregaEntit 109
#define IDH_PRINCIPALIFUNZIONALITDIGEOSIMFOUNDATION 10
#define IDH_DisgregaEntit 110
#define IDH_RetinoGEOsim 111
#define IDH_Gscopy2acadobj 112
#define IDH_Gestionesetdivisibilit 113
#define IDH_Dimensionamentoblocchieattributi 114
#define IDH_Gestionemodellideipiani 115
#define IDH_Salvaecaricasetdipiani 116
#define IDH_Gestionemodellidivisualizzazionedeipiani 117
#define IDH_Nascondiattributisovrapposti 118
#define IDH_Portainprimopiano 119
#define IDH_Aggiungientitadungruppoesistente 120
#define IDH_Rimuovientitdaungruppoesistente 121
#define IDH_INTERROGAZIONIEAGGIORNAMENTODELDATABASE 122
#define IDH_Attributientit 124
#define IDH_Interrogazioneemodificatramitepannellodellasessionedilavoro 125
#define IDH_Aggiornamentodegliattributi 126
#define IDH_Listavalorigiinseriti 127
#define IDH_Funzionedisuggerimentovalore 128
#define IDH_Operatorimatematici 129
#define IDH_AreagestionaleGEOorganizer 12
#define IDH_Attributidelletabellesecondarie 130
#define IDH_Interrogazionedinamica 131
#define IDH_Copiavaloridiattributi 132
#define IDH_Appartenenzaentitbloccata 133
#define IDH_Evidenziazioneoggettidasalvare 134
#define IDH_Evidenziazioneoggettirifiutati 135
#define IDH_Trasferimentovaloridatabellasecondaria 136
#define IDH_ANALISIDELLABANCADATILAFUNZIONEDIFILTRO 137
#define IDH_Selezionedeglioggetti 139
#define IDH_AreaOperativaGEOeditor 13
#define IDH_Selezionespaziale 140
#define IDH_Selezionemediantelusodissfilter 141
#define IDH_Metodidirestituzionedeirisultatidiunfiltro 142
#define IDH_Evidenziazionerisultatifiltro 143
#define IDH_Esportazionerisultatifiltro 144
#define IDH_Statisticherisultatifiltro 145
#define IDH_Sfogliaoggettigraficirisultatodelfiltro 146
#define IDH_OpzioneNessuno 147
#define IDH_ImpostazionedellecondizioniSQL 148
#define IDH_LAFUNZIONEDIFILTROTEMATICO 149
#define IDH_GESTIONEDELLECONNESSIONIADATABASE 14
#define IDH_Modalitoperative 151
#define IDH_Risultatidelfiltro 152
#define IDH_RICERCAPERSENSORI 153
#define IDH_Selezionedeisensori 155
#define IDH_Selezioneentitdarilevare 156
#define IDH_Regoledirilevamento 157
#define IDH_Rilevamentospaziale 158
#define IDH_RilevamentoSQL 159
#define IDH_Strumenti 160
#define IDH_Esportazioneglobale 161
#define IDH_EsportazionepersensoreStatistiche 162
#define IDH_Statistiche 163
#define IDH_Modificaentitrilevate 164
#define IDH_RICERCHETOPOLOGICHE 165
#define IDH_Regoleperlevisitetopologiche 167
#define IDH_Ricercadelpercorsopibreve 168
#define IDH_Ricercaperpropagazione 169
#define IDH_Concettidibasesuidatabase 16
#define IDH_CLASSIGRIGLIA 170
#define IDH_Aggiornamentomanualeattributidellecelle 171
#define IDH_Aggiornamentocelledaelevazioneoggettiautocad 172
#define IDH_Aggiornamentodadatabaseesterno 173
#define IDH_Drape 174
#define IDH_InterpolazionespazialeIDWInverseDistanceWeighted 175
#define IDH_Parametridicalcolo 176
#define IDH_Calcolodelladirezionedelflusso 177
#define IDH_Ricercadelbacino 178
#define IDH_Conteggiodellecelleamonte 179
#define IDH_Sorgentidati 17
#define IDH_Visualizzazionedivalliecrinali 180
#define IDH_Visualizzazionecurvedilivello 181
#define IDH_SEGMENTAZIONEDINAMICA 182
#define IDH_Abilitazioneallasegmentazionedinamica 183
#define IDH_Inserimentodatidisegmentazionedinamica 184
#define IDH_Calibrazione 185
#define IDH_Analisisegmentazionedinamica 186
#define IDH_UTILITA 187
#define IDH_Controllotabelleprincipali 189
#define IDH_Verificareunasorgentedati 18
#define IDH_Controlloclassi 190
#define IDH_Sincronizzazioneclassi 191
#define IDH_Ottimizzazionedisegni 192
#define IDH_Ottimizzareidisegnidiunaclasse 194
#define IDH_Creazioneautomaticaclassi 195
#define IDH_Listedisceltavaloriperattributi 196
#define IDH_Modalitguidata 197
#define IDH_ListavaloriGEOsim 198
#define IDH_Listavaloridadatabaseesterno 199
#define IDH_Usareunasorgentedati 19
#define IDH_InformazionigeneralisuGEOsim 1
#define IDH_Modalitmanuale 200
#define IDH_ListadisceltaobbligataaduecolonneTAB 201
#define IDH_ListedisceltaaduecolonneREF 202
#define IDH_ListadisceltaobbligataadunacolonnaFDF 203
#define IDH_ListadisceltaadunacolonnaDEF 204
#define IDH_Riconnessionedatabase 205
#define IDH_LopzioneGEOlisp 206
#define IDH_CreazionedeifileDWF_DWG 207
#define IDH_Creazionedelsinotticodiriferimento 208
#define IDH_CreazionevistePostgreSQLperaccessoaidatidaapplicazioniesterne 209
#define IDH_ConfigurazionediunasorgentedatifileUDL 20
#define IDH_CreazionediunfilediprogettoQuantumGIS 210
#define IDH_SezioneParametrigenerali 211
#define IDH_SezioneClassidientit 212
#define IDH_SezioneRaggruppamentoclassi 213
#define IDH_Limitazioni 214
#define IDH_Storicizzazionedeidati 215
#define IDH_Collegamentoatabellestoriche 216
#define IDH_Limitazioni18_13_2 217
#define IDH_ConversionedatidaversioneprecedentediGEOsim 218
#define IDH_EsportazionedatiinGoogleEarth 219
#define IDH_FileUDLeREQUIRED 21
#define IDH_Esportazionedatiinshape 220
#define IDH_PERSONALIZZAZIONEDELSISTEMA 221
#define IDH_Gestionedeinodidirete 223
#define IDH_Caricamentolispdipersonalizzazione 224
#define IDH_Latoserver 226
#define IDH_PLOTTAGGIO 227
#define IDH_Ilcomandodistampa 229
#define IDH_Strutturadiungenericofile_REQUIRED 22
#define IDH_Impostazionedelfattorediscala 230
#define IDH_Sceltatipologiaplottata 231
#define IDH_Opzioniplottata 232
#define IDH_Sceltadelformatodelfoglio 233
#define IDH_Layoutdipagina 234
#define IDH_Comandolispperilplottaggio 235
#define IDH_CreazionediundisegnodiAutoCAD 236
#define IDH_LINGUAGGIODIPROGRAMMAZIONEGEOlisp 237
#define IDH_DatidiGEOlisp 239
#define IDH_OverloadingdifileUDL 23
#define IDH_ProgrammiinGEOlisp 240
#define IDH_ElencosinteticodellefunzionidiGEOlisp 241
#define IDH_Funzioniaritmetiche 242
#define IDH_Funzioniperiltrattamentodellestringhe 243
#define IDH_Funzionidiuguaglianzaecondizione 244
#define IDH_Funzioniperlagestionedisimboli 245
#define IDH_Funzioniperlagestionediapplicazioni 246
#define IDH_Funzioniperlagestionedifunzioni 247
#define IDH_Funzionidiconversione 248
#define IDH_Funzionivarie 249
#define IDH_Limitazioni3_3_6 24
#define IDH_Funzionidataeora 250
#define IDH_Funzioniperilcontrollodellagrafica 251
#define IDH_Funzioniperdatabase 252
#define IDH_CatalogodellefunzioniGEOlisp 253
#define IDH_NUOVEFUNZIONALIT 254
#define IDH_LimitazioniperPostgreSQL 25
#define IDH_LimitazioniperOracle 26
#define IDH_ACCESSOALLEFUNZIONALITDIGEOSIM 27
#define IDH_Configurazionedelsistema 29
#define IDH_GESTIONEDEITEMATISMI 30
#define IDH_Blocchi 32
#define IDH_InserimentodiunnuovosimbolograficonellalibreriadiGEOsim 33
#define IDH_Tipilinea 34
#define IDH_Stilitesto 35
#define IDH_Riempimenti 36
#define IDH_AggiornareitematismisuiclientdiGEOsim 37
#define IDH_Puliziadeidisegni 38
#define IDH_GESTIONEDEGLIUTENTI 39
#define IDH_StrutturaGEOsim 3
#define IDH_Creazioneutente 41
#define IDH_Cancellazioneutente 42
#define IDH_Modificautente 43
#define IDH_Abilitazioneaidati 44
#define IDH_Comandi 45
#define IDH_Modificapassword 46
#define IDH_GESTIONEDEIPROGETTI 47
#define IDH_Creazioneprogetto 49
#define IDH_Configurazionidisponibili 4
#define IDH_Cancellazionedelprogetto 50
#define IDH_Modificaprogetto 51
#define IDH_GESTIONECLASSIDIENTIT 52
#define IDH_Creazioneclassidientit 54
#define IDH_Creazioneclassidientitgruppi 55
#define IDH_Creazioneclassidientitgriglia 56
#define IDH_Creazioneclassidientitsimulazione 57
#define IDH_Creazioneclassiconcollegamentoadatigiesistenti 58
#define IDH_Caratteristichegrafichedaticollegati 59
#define IDH_NozionidibasediGEOsim 5
#define IDH_CollegamentoDBstrutturatabelladaticollegati 60
#define IDH_Caratteristichegrafichedellentit 61
#define IDH_Formatodatigeometrici 62
#define IDH_Connessionifraclassidientit 63
#define IDH_Tabellediunaclasse 64
#define IDH_Cancellazioneclassidientit_ 65
#define IDH_Modificaclassidientit 66
#define IDH_Copiadelleclassidientit 67
#define IDH_Copiadiclassigruppo 68
#define IDH_GestioneSetdiclassi 69
#define IDH_InstallazionediGEOsimClient 6
#define IDH_GestioneTabelleSecondarie 70
#define IDH_Impostazionedelsistemadicoordinate 71
#define IDH_Creazionediunbloccodiriferimentodegliattributivisibili 72
#define IDH_Funzionidicalcolodegliattributi 73
#define IDH_Topologiadinamica 74
#define IDH_Creazionediunatopologia 75
#define IDH_Aggiornamentodinamicodellagrafica 76
#define IDH_GESTIONESESSIONIDILAVORO 77
#define IDH_Creazionesessionedilavoro 79
#define IDH_AggiornamentodiGEOsimClient 7
#define IDH_Estrazionedatinellasessionedilavoro 80
#define IDH_Comandogsddimposta 81
#define IDH_Selezionezonaperposizione 82
#define IDH_SelezionezonadacatalogodiQuery 83
#define IDH_Selezionezonaperentit 84
#define IDH_Selezioneclassi 85
#define IDH_Estrazione 86
#define IDH_Pannellodellasessionedilavoro 87
#define IDH_Usodeltastodestrodelmouse 88
#define IDH_Sessionidilavorocongelate 89
#define IDH_InstallazionediGEOsimServer 8
#define IDH_Salvataggiodeidati 90
#define IDH_Uscitadaunasessionedilavoroattiva 91
#define IDH_Cancellazionedellasessionedilavoro 92
#define IDH_Recuperodellasessionedilavoro 93
#define IDH_Elencosessionidilavoro 94
#define IDH_Sistemadinotifica 95
#define IDH_COMANDIDIGEOSIM 96
#define IDH_ComandiAutoCADinGEOsim 98
#define IDH_CancellaErase 99
#define IDH_AggiornamentodiGEOsimServer 9
