/*************************************************************************/
/*   GS_FIND.H                                                           */
/*************************************************************************/

#ifndef _gs_find_h
#define _gs_find_h 1

//****************************************************************************
int gs_filter_sql(void);
int gs_filter_fas(void);
int gs_find_addr(void);
int gs_impost_estrqry(void);
int gs_zoom_in(void);

#endif